name: Build
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build-and-test:
        name: Build & Test
        uses: dnd-mapp/actions/.github/workflows/build.yml@main
