name: Build
permissions:
    contents: read
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    execute:
        name: Execute
        uses: dnd-mapp/actions/.github/workflows/build.yml@main
