name: Bump version
permissions:
    contents: write
    pull-requests: write
on:
    workflow_dispatch:
        inputs:
            version:
                required: true
                description: What kind of release is this going to be?
                type: choice
                options:
                    - major
                    - minor
                    - patch
jobs:
    bump-version:
        name: Execute
        uses: dnd-mapp/actions/.github/workflows/bump-version@main
        secrets: inherit
        with:
            version: ${{ inputs.version }}
