name: Publish
permissions:
    contents: read
    packages: write
on:
    push:
        branches:
            - main
    release:
        types:
            - released
jobs:
    execute:
        name: Execute
        uses: dnd-mapp/actions/.github/workflows/publish-docker-image.yml@main
        secrets: inherit
        with:
            image-name: ghcr.io/dnd-mapp/dma-asu
