name: Release
permissions:
    contents: write
on:
    pull_request:
        types:
            - closed
jobs:
    execute:
        name: Execute
        uses: dnd-mapp/actions/.github/workflows/release.yml@main
        secrets: inherit
